Fix build with GCC 4.6 -Werror=unused-but
* similar to c200e893ccd29c2d6250bcc08f5f6c245a504c1a but for s3c2410
  too

* This patch fixes the following build failures:
  src/cpu/s3c2410/s3c24xx-mci.c: In function 'mmc_block_read':
  src/cpu/s3c2410/s3c24xx-mci.c:140:7: error: variable 'resp' set but not used [-Werror=unused-but-set-variable]

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>